redis:
  image: redis:latest
  restart: always
  command: redis-server --appendonly yes
  ports:
    - '6379:6379'
  volumes:
    - /tmp

go_redis:
  build: .
  environment:
    TZ: Asia/Tokyo
  links:
    - redis
